<?php

namespace App\Services\HelpDesk;

use App\Models\HelpDesk;
use App\Models\HelpDeskInbox;
use App\Models\HelpDeskSpace;
use App\Models\User;
use App\Models\Workspace;
use Illuminate\Support\Facades\DB;

/**
 * Gets a workspace's Help Desk, creating it the first time somebody opens the app
 * (docs/features/help-desk.md, slice 2).
 *
 * Provisioning is LAZY for the same reason workspace settings are: switching the app on is a
 * flag, and a workspace that turns Help Desk on to look at it should not have rows written for
 * a support operation it never sets up. The first visit by somebody who can administer it is
 * what creates the Help Desk and its first inbox.
 *
 * The first inbox is part of provisioning rather than something to be created later, because
 * inbox-level access (FR-1.7) needs an inbox to grant — a Help Desk with none is a member
 * screen where the access column can only ever be empty.
 */
class HelpDeskProvisioner
{
    public function __construct(private readonly InboundAddressGenerator $addresses) {}

    /** The workspace's Help Desk, or null if it has never been set up. */
    public function existing(Workspace $workspace): ?HelpDesk
    {
        return HelpDesk::query()
            ->withoutGlobalScopes()
            ->where('tenant_id', $workspace->id)
            ->first();
    }

    /**
     * The workspace's Help Desk, created if this is the first time.
     *
     * In a transaction with the first inbox: a Help Desk that exists without one is a state
     * every screen after this would have to carry a branch for.
     */
    public function for(Workspace $workspace, ?User $creator = null): HelpDesk
    {
        $existing = $this->existing($workspace);

        if ($existing) {
            return $existing;
        }

        return DB::transaction(function () use ($workspace, $creator) {
            /*
             * Re-read inside the transaction. Two people opening Help Desk at the same moment
             * on a workspace that has never had one is not exotic — it is what happens when an
             * admin shares the link — and `help_desks.tenant_id` is unique, so the loser of
             * that race would get a database error instead of a Help Desk.
             */
            $helpDesk = $this->existing($workspace);

            if ($helpDesk) {
                return $helpDesk;
            }

            $helpDesk = HelpDesk::create([
                'tenant_id' => $workspace->id,
                'name' => $workspace->name,
                'created_by' => $creator?->id,
            ]);

            /*
             * The first space (Workspace & Inbox Assignment §7, §16).
             *
             * Created here for the same reason the first inbox is: the hierarchy is Help Desk →
             * space → inbox, and an inbox belonging to no space is a state §12 tolerates for
             * inboxes that predate a space, not one a fresh Help Desk should start in.
             */
            $space = HelpDeskSpace::create([
                'tenant_id' => $workspace->id,
                'help_desk_id' => $helpDesk->id,
                'name' => (string) config('help-desk.default_space', 'Customer Support'),
                'created_by' => $creator?->id,
            ]);

            /*
             * The inbox gets its inbound address here, at creation, and never from a form
             * (Inbound Email requirements §2). An inbox without one is an inbox nothing can be
             * forwarded to — a state the requirements do not allow to exist, so it does not
             * exist for even one save.
             */
            $inbox = $this->addresses->assign(HelpDeskInbox::create([
                'tenant_id' => $workspace->id,
                'help_desk_id' => $helpDesk->id,
                'help_desk_space_id' => $space->id,
                'name' => (string) config('help-desk.default_inbox', 'Support'),
                'created_by' => $creator?->id,
            ]));

            /*
             * The space starts the Setup Inbox flow at step 2, pointed at that inbox.
             *
             * Step 1 asks for a name, and this inbox has one — so the flow opens where there is
             * actually something left to do: connecting the address customers write to. An
             * inbox generated by provisioning receives nothing until somebody forwards to it,
             * which is exactly what "has not completed its initial inbox setup" means.
             */
            $space->forceFill([
                'setup_inbox_id' => $inbox->id,
                'setup_step' => HelpDeskSpace::STEP_ADDRESSES,
            ])->save();

            return $helpDesk;
        });
    }
}
